### ISSUE TITLE
this plugin is so helpful,hope to suppourt 2.5

### ISSUE THREAD

**Issue by junerver** [drakeet/MultiTypeTemplates#1]

**Comment by plusend** [comment]
+ 1

**Comment by drakeet** [comment]
I am very busy recently, so if someone can provide Pull Request will be great.

**Comment by drakeet** [comment]
1.2.0 has been released. Please check https://plugins.jetbrains.com/plugin/9202 or https://github.com/drakeet/MultiTypeTemplates/releases.
